<a href="https://colab.research.google.com/github/krinapatel1211/Pytorch_Tutorial/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Resource Notebook: - https://www.learnpytorch.io/00_pytorch_fundamentals/
### Github: - https://github.com/mrdbourke/pytorch-deep-learning

In [1]:
# !nvidia-smi

In [2]:
import torch
# print(torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
torch.tensor(7).dtype

torch.int64

In [5]:
scaler.ndim

0

In [6]:
scaler.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7,8],[9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([9, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[[1,2,3],
                [2,6,9],
              [4,5,7]]])

In [16]:
TENSOR

tensor([[[1, 2, 3],
         [2, 6, 9],
         [4, 5, 7]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 6, 9],
        [4, 5, 7]])

In [20]:
TENSOR = torch.tensor([[[[1,2,3],
                         [4,5,6]],
                       [[1,2,5],
                       [3,2,6]]]])

In [21]:
TENSOR.ndim

4

In [22]:
TENSOR.shape

torch.Size([1, 2, 2, 3])

In [23]:
torch.Size([2, 3, 4, 3])

torch.Size([2, 3, 4, 3])

In [24]:
TENSOR = torch.tensor([[[[1,2,3],
                         [1,2,3],
                         [1,2,3],
                         [1,2,3]],
                        [[1,2,3],
                         [1,2,3],
                         [1,2,3],
                         [1,2,3]],
                        [[1,2,3],
                         [1,2,3],
                         [1,2,3],
                         [1,2,3]]],

                       [[[1,2,3],
                         [1,2,3],
                         [1,2,3],
                         [1,2,3]],
                        [[1,2,3],
                         [1,2,3],
                         [1,2,3],
                         [1,2,3]],
                        [[1,2,3],
                         [1,2,3],
                         [1,2,3],
                         [1,2,3]]]])

In [25]:
TENSOR.ndim

4

In [26]:
TENSOR.shape

torch.Size([2, 3, 4, 3])

### Random tensors

In [27]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5612, 0.4845, 0.8393, 0.6920],
        [0.9278, 0.6801, 0.0536, 0.6723],
        [0.3705, 0.3930, 0.4657, 0.2666]])

In [28]:
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[7.5450e-01, 5.1985e-02, 5.8453e-01, 1.7136e-01, 8.6311e-01,
          9.5544e-02, 8.0378e-01, 4.2836e-02, 4.6673e-01, 6.8045e-02],
         [6.7652e-01, 2.0786e-02, 8.0928e-01, 9.8782e-01, 3.8588e-01,
          4.7867e-01, 2.9759e-01, 9.5332e-01, 1.3826e-01, 1.3347e-01],
         [4.8548e-01, 8.7774e-01, 4.3191e-01, 4.3932e-01, 4.7338e-01,
          9.3273e-01, 8.2708e-01, 9.9399e-01, 1.8382e-01, 2.9357e-01],
         [5.1953e-01, 3.9835e-01, 3.4508e-01, 8.2765e-01, 7.5163e-01,
          6.5582e-01, 8.6269e-01, 7.9309e-02, 3.4718e-02, 3.7758e-01],
         [3.0148e-01, 8.0151e-01, 5.7564e-01, 9.4230e-01, 3.3357e-01,
          4.0652e-02, 8.2585e-01, 5.2019e-01, 3.1226e-02, 6.4687e-01],
         [1.5658e-01, 5.2832e-01, 7.1669e-01, 1.3124e-01, 1.6092e-02,
          4.4162e-01, 7.9853e-01, 1.9382e-01, 6.0410e-01, 5.9949e-01],
         [9.9413e-01, 8.5012e-01, 9.9868e-01, 6.4822e-01, 8.3444e-01,
          5.5203e-01, 7.4727e-01, 6.3358e-01, 6.1395e-01, 6.6106e-01],
         [5.0

In [29]:
random_tensor.ndim

3

In [30]:
random_image_size_tensor = torch.rand(size=(224, 224,3)) #height, widthe, color channel
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [31]:
torch.rand(3,3)

tensor([[0.6559, 0.0100, 0.2103],
        [0.3447, 0.2391, 0.6553],
        [0.2122, 0.7066, 0.8244]])

In [32]:
torch.rand(5,10,10)

tensor([[[0.3043, 0.5036, 0.7045, 0.1282, 0.9050, 0.5194, 0.2556, 0.0595,
          0.8884, 0.4736],
         [0.6266, 0.2286, 0.1948, 0.5871, 0.9871, 0.1892, 0.3814, 0.1521,
          0.3084, 0.6797],
         [0.3327, 0.7766, 0.3421, 0.9381, 0.1405, 0.7450, 0.4216, 0.7993,
          0.9012, 0.8299],
         [0.9762, 0.9749, 0.2288, 0.4351, 0.3412, 0.2526, 0.3232, 0.8738,
          0.8124, 0.3561],
         [0.3983, 0.1538, 0.2886, 0.2015, 0.4688, 0.4107, 0.6064, 0.2620,
          0.3613, 0.2642],
         [0.4265, 0.3587, 0.5640, 0.1976, 0.0827, 0.8017, 0.9461, 0.3100,
          0.4124, 0.9551],
         [0.3836, 0.9530, 0.9092, 0.8431, 0.3742, 0.9262, 0.7580, 0.6412,
          0.4736, 0.1368],
         [0.0186, 0.2080, 0.4694, 0.9857, 0.9748, 0.1308, 0.9466, 0.9464,
          0.3148, 0.3063],
         [0.2907, 0.9086, 0.2657, 0.6306, 0.6218, 0.9049, 0.7230, 0.4752,
          0.5779, 0.1714],
         [0.4443, 0.6924, 0.1975, 0.1179, 0.6990, 0.5529, 0.5964, 0.4622,
          0.7216,

## Zeros and ones

In [33]:
zeros = torch.zeros(size=(3,4))

In [34]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
ones.dtype

torch.float32

## Range of tensors and tensors-like

In [37]:
torch.range(0, 10)

<ipython-input-37-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
a = torch.arange(start=0, end=1300, step=77)

In [40]:
a_like = torch.zeros_like(input=a)
a_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
a_like = torch.ones_like(input=a)
a_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor datatypes

In [42]:
float_32_tensor = torch.tensor([3,6,9],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [43]:
float_32_tensor.dtype

torch.float16

In [44]:
b = float_32_tensor.type(torch.half)
b

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
b*float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [46]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [47]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [48]:
float_32_tensor.device

device(type='cpu')

In [49]:
float_32_tensor.size() ## size() is a function here

torch.Size([3])

In [50]:
float_32_tensor.shape

torch.Size([3])

## Manipulating Tensors (tensor operations)


In [51]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [52]:
tensor*10

tensor([10, 20, 30])

In [53]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [54]:
tensor-10

tensor([-9, -8, -7])

In [55]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [56]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [57]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [58]:
torch.div(tensor, 5)

tensor([0.2000, 0.4000, 0.6000])

In [59]:
# 1. Emelent-wise multiplication (multiplication with scaler)
# 2. Matrix multiplication (dot product)

tensor * tensor


tensor([1, 4, 9])

In [60]:
torch.matmul(tensor, tensor) # 1*1 + 2*2 + 3*3 = 14

tensor(14)

In [61]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]

print(value)

tensor(14)
CPU times: user 762 µs, sys: 968 µs, total: 1.73 ms
Wall time: 3.74 ms


In [62]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 33 µs, sys: 0 ns, total: 33 µs
Wall time: 36.2 µs


tensor(14)

In [63]:
# The two rules for matrix multiplications
# 1. the inner dimensions should match - (2,3) * (3,2) will work but (3,2)*(3,2) will not work
# 2. The resulting matrix will have the shape of the outer dimensions - (5,7)*(7,8) --> (5,8)

In [64]:
a = torch.rand(5,7)
b = torch.rand(7, 8)

torch.matmul(a, b)


tensor([[2.8430, 1.9804, 2.0715, 2.7691, 2.2068, 1.5960, 2.8648, 2.3114],
        [1.7848, 1.6629, 1.5639, 1.7810, 2.3749, 0.6907, 2.5318, 1.5486],
        [2.6614, 1.8398, 2.2532, 2.8302, 2.2861, 1.4719, 2.8176, 2.2741],
        [2.6627, 1.3986, 2.1253, 2.5245, 2.0097, 1.3429, 2.5477, 2.2386],
        [2.0799, 1.7882, 1.7187, 2.4263, 2.1108, 1.1631, 2.3645, 1.7248]])

In [65]:
a = torch.rand(5,7)
b = torch.rand(5,7)
torch.matmul(a,b.T)

tensor([[0.8199, 0.9521, 0.9682, 1.3474, 0.9930],
        [2.3242, 1.9397, 2.3819, 3.3760, 2.4877],
        [1.9552, 1.5184, 2.3744, 2.7944, 1.6379],
        [2.1888, 2.1395, 2.2764, 3.4959, 2.4708],
        [2.3796, 1.9803, 2.7097, 3.5628, 2.3556]])

In [66]:
a @ b.T

tensor([[0.8199, 0.9521, 0.9682, 1.3474, 0.9930],
        [2.3242, 1.9397, 2.3819, 3.3760, 2.4877],
        [1.9552, 1.5184, 2.3744, 2.7944, 1.6379],
        [2.1888, 2.1395, 2.2764, 3.4959, 2.4708],
        [2.3796, 1.9803, 2.7097, 3.5628, 2.3556]])

## Tensor Aggregation(Finding the min, max, mean, sum etc)

In [67]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [68]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [69]:
x.dtype

torch.int64

In [70]:
torch.mean(x.type(torch.float32)), x.dtype, x.type(torch.float64).mean()

(tensor(46.), torch.int64, tensor(46., dtype=torch.float64))

In [71]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [72]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [73]:
x[9], x[x.argmax()]

(tensor(91), tensor(91))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Returns a view of an input tensor of certain shape but keep the same memory as the original tensor. changing the new tensor will also change the original tensor
* stacking - combine multiple tensors on top of one another (vstck) or side by side (hstack)
* Squeeze = removes all '1' dimension to a target tensor
* Unsqueeze - add dimension to existing tensor to a specific dimension
* permutes - swap order or dimensions

In [74]:
x = torch.arange(1., 10.)
x.shape, x

(torch.Size([9]), tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [75]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [76]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [78]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [79]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [80]:
x_hstacked = torch.hstack([x,x,x,x,x,x,x])
x_hstacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [81]:
x_vstacked = torch.vstack([x,x,x,x,x,x,x,x])
x_vstacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [82]:
x = torch.zeros([1,2,1,4])
x

tensor([[[[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]]]])

In [83]:
y = x.squeeze()
y.shape

torch.Size([2, 4])

In [84]:
y = x.squeeze(dim=2)
y.shape

torch.Size([1, 2, 4])

In [85]:
z = y.unsqueeze(dim=1)
z.shape

torch.Size([1, 1, 2, 4])

In [86]:
w = z.unsqueeze(dim=3)
w.shape

torch.Size([1, 1, 2, 1, 4])

In [87]:
x = torch.randn(2,3,5)
x.shape

torch.Size([2, 3, 5])

In [88]:
y = x.permute(2,0,1)
y.shape

torch.Size([5, 2, 3])

In [89]:
x_image = torch.rand(size=(224, 224,3))
x_permuted_image = x_image.permute(2,1,0)
x_permuted_image.shape

torch.Size([3, 224, 224])

In [90]:
x_image[0,0,0] = 987

In [91]:
x_permuted_image[0,0,0]

tensor(987.)

## Selecting data from tensors (Indexing)

In [92]:
x = torch.arange(1, 10).reshape(1,1,3,3)
x, x.shape

(tensor([[[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]]),
 torch.Size([1, 1, 3, 3]))

In [93]:
x[0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [94]:
x[0,0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [95]:
x[0,0,0]

tensor([1, 2, 3])

In [96]:
x[0][0][0]

tensor([1, 2, 3])

In [97]:
x[0,0,0,2]

tensor(3)

In [98]:
x[0,0,1,1]

tensor(5)

In [99]:
x[0,0,2,2]

tensor(9)

In [100]:
x[:,:,:,1 ]

tensor([[[2, 5, 8]]])

In [101]:
x[0,0,1,1]

tensor(5)

In [102]:
x[:,0,0,:]

tensor([[1, 2, 3]])

In [103]:
x[:,:,:,2]

tensor([[[3, 6, 9]]])

## PyTorch tensors and Numpy
* Data in NumPy, want in PyTorch tensor --> `torch.from_numpy(ndarray`
* PyTorch tensor --> NumPy --> `torch.Tensor.numpy()`

In [104]:
array = np.arange(1.0,8.0)
array.dtype

dtype('float64')

In [105]:

tensor = torch.from_numpy(array) # when converting from numpy to pytorch, pytorch
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [106]:
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [107]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [108]:
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## PyTorch Reproducibility (trying to take random out of random)

In [109]:
a = torch.rand(3,4)
b = torch.rand(3,4)
a, b, a==b, a!=b, a>b

(tensor([[0.9225, 0.7543, 0.8201, 0.5656],
         [0.8789, 0.1116, 0.0019, 0.1407],
         [0.3455, 0.8193, 0.5590, 0.7122]]),
 tensor([[0.0856, 0.3929, 0.5048, 0.4027],
         [0.8741, 0.2718, 0.0674, 0.1079],
         [0.3085, 0.9388, 0.8754, 0.5192]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]),
 tensor([[ True,  True,  True,  True],
         [ True, False, False,  True],
         [ True, False, False,  True]]))

In [110]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
d = torch.rand(3,4)
c, d, c==d,


(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [111]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

In [112]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [113]:
# count number of devices
torch.cuda.device_count()

1

In [115]:
# getting pytorch tensors and models on the GPU
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [116]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [119]:
# moving tensors back to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])