<a href="https://colab.research.google.com/github/krinapatel1211/Pytorch_Tutorial/blob/main/PyTorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import torch
import torch.nn as nn
import torch.nn.functional as F
device = 'cuda' if torch.cuda.is_available else 'cpu'
print(device)

block_size=8
batch_size=4

cuda


In [2]:
# !pip list

# New section

TENSORS

In [3]:
import torch
import numpy as np


In [4]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 0.2485, -0.1923, -0.0692,  0.8658],
        [-1.8725, -0.4667, -0.2815, -0.4428],
        [ 1.2379,  0.2129,  1.9143,  2.4849]])

In [5]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[-7.4170e-01,  6.2364e-01, -1.5993e-01, -6.1518e-01],
         [-1.6700e-03,  6.4837e-01, -1.6945e-01,  9.5298e-01],
         [-8.6613e-01, -1.3451e-01, -5.9218e-02, -1.8562e+00]],

        [[-2.5712e-02,  3.8451e-01,  2.3370e+00,  8.8942e-02],
         [-1.0793e+00,  6.7824e-01,  4.0232e-01, -4.7740e-01],
         [ 1.4674e+00, -9.4133e-01, -5.7687e-02, -1.2727e+00]]])

In [6]:
tensor_3d.dtype

torch.float32

In [7]:
tensor_2d.dtype

torch.float32

In [8]:
# create tensor out of numpy array, now the tensor is of type float64

np1 = np.random.randn(3,4,2)

my_tensor = torch.tensor(np1)
my_tensor

tensor([[[-0.1445, -1.4634],
         [ 1.3906,  0.8508],
         [-0.7664,  2.3248],
         [-1.0312, -0.3289]],

        [[ 0.6983,  0.6638],
         [-2.4286,  1.3436],
         [-0.2677, -0.3419],
         [ 0.7353,  0.4454]],

        [[-1.3872,  0.5877],
         [ 0.2713, -0.7558],
         [-0.7783,  0.6519],
         [ 1.3114,  1.0250]]], dtype=torch.float64)

## **TENSOR** **OPERATIONS**

In [9]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
my_torch = my_torch.reshape(5, -1)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [12]:
my_torch = my_torch.reshape(1, -1)
my_torch

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
randint = torch.randint(-100, 100, (6,2))
randint

tensor([[ 92,  30],
        [-51,  72],
        [-52, -65],
        [-79, -82],
        [ 64,  21],
        [ 86, -80]])

In [14]:
tensor = torch.tensor([[0.1, 1.2],[2.2,3.1],[4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [15]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
input = torch.empty(2,3)
input

tensor([[0.0000e+00, 0.0000e+00, 9.1084e-44],
        [0.0000e+00, 4.1408e-07, 3.1693e-41]])

In [18]:
#
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [19]:
linespace = torch.linspace(3, 10, steps=5)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [20]:

logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [21]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
a = torch.empty((2,3), dtype=torch.int64)

empty_like = torch.empty_like(a)
empty_like


tensor([[3182391460041326592, 7310593858020254331, 3616445622929465956],
        [6066686442236554548, 3689638012019946544, 6500164555030999342]])

## SOME TORCH **FUNCTIONS**

In [23]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 0, 0, 1, 1, 1, 1, 1, 1])

In [24]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5,6,7])), dim=0)
out

tensor([1, 2, 3, 4, 5, 6, 7])

In [25]:
tensor = torch.tril(torch.ones(5,5))
tensor

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [26]:
torch.tril(torch.tensor([[1,2,3],[4,5,6]]), diagonal=1)

tensor([[1, 2, 0],
        [4, 5, 6]])

In [27]:
torch.triu(torch.tensor([[1,6],[7,8],[9,5],[4,7]]), diagonal=0)

tensor([[1, 6],
        [0, 8],
        [0, 0],
        [0, 0]])

In [28]:
input_tensor = torch.tensor([[1,6],[7,8]])
masked_tensor = torch.tensor([[True, False], [True, True]])

torch.masked_fill(input_tensor, masked_tensor, value=1)

tensor([[1, 6],
        [1, 1]])

In [29]:
input = torch.zeros(2,3,4)
output = input.transpose(0, 2)
output.shape

torch.Size([4, 3, 2])

In [30]:
input

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [31]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,6,8])
tensor_3 = torch.tensor([9,3,5])

stacked_tensor = torch.stack([tensor_1, tensor_2, tensor_3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 6, 8],
        [9, 3, 5]])

In [32]:
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))

tensor([ 8.1241, -3.0033,  7.6670], grad_fn=<SqueezeBackward4>)


In [34]:
tensor1 = torch.tensor([1., 2., 3.])
softmax_output = F.softmax(tensor1, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])