<a href="https://colab.research.google.com/github/krinapatel1211/Pytorch_Tutorial/blob/main/PyTorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
device = 'cuda' if torch.cuda.is_available else 'cpu'
print(device)

block_size=8
batch_size=4

cuda


In [2]:
# !pip list

# New section

TENSORS

In [3]:
import torch
import numpy as np


In [4]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 0.1963, -2.0318,  0.2402, -0.3236],
        [ 1.1222, -0.9836, -0.7352, -0.5260],
        [ 0.6405,  1.3071,  1.3076, -0.1291]])

In [5]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[-0.9586, -1.3645,  0.2123, -0.6144],
         [-0.6580, -0.6291, -1.2965,  0.8183],
         [-1.2309,  1.8250, -0.1847, -0.8453]],

        [[ 0.1314, -1.2555,  1.0768,  0.4864],
         [ 0.9921,  1.1392, -0.4768,  0.0485],
         [-0.0700, -0.0054,  0.9473, -0.8873]]])

In [6]:
tensor_3d.dtype

torch.float32

In [7]:
tensor_2d.dtype

torch.float32

In [8]:
# create tensor out of numpy array, now the tensor is of type float64

np1 = np.random.randn(3,4,2)

my_tensor = torch.tensor(np1)
my_tensor

tensor([[[ 0.6161,  0.6951],
         [ 0.1742,  0.0110],
         [ 1.8145,  0.7027],
         [-0.2994, -0.2108]],

        [[ 0.0605,  0.1274],
         [ 0.8148,  0.5566],
         [ 0.3888,  0.9365],
         [-2.4209, -0.1780]],

        [[ 0.1603,  0.1339],
         [-0.2872, -1.3245],
         [-0.9310,  0.5053],
         [-0.5939, -2.6130]]], dtype=torch.float64)

## **TENSOR** **OPERATIONS**

In [9]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
my_torch = my_torch.reshape(5, -1)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [12]:
my_torch = my_torch.reshape(1, -1)
my_torch

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
randint = torch.randint(-100, 100, (6,2))
randint

tensor([[-58, -33],
        [-31,  33],
        [ 80,  48],
        [ 77,  22],
        [-40, -44],
        [-49,  81]])

In [14]:
tensor = torch.tensor([[0.1, 1.2],[2.2,3.1],[4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [15]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
input = torch.empty(2,3)
input

tensor([[-1.1416e-28,  3.2849e-41, -1.1422e-28],
        [ 3.2849e-41,  0.0000e+00,  0.0000e+00]])

In [18]:
#
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [19]:
linespace = torch.linspace(3, 10, steps=5)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [20]:

logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [21]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
a = torch.empty((2,3), dtype=torch.int64)

empty_like = torch.empty_like(a)
empty_like


tensor([[134899711409568, 134899711409568,              32],
        [            112, 100704773069913,               0]])

## SOME TORCH **FUNCTIONS**

In [23]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 0, 0])

In [24]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5,6,7])), dim=0)
out

tensor([1, 2, 3, 4, 5, 6, 7])

In [25]:
tensor = torch.tril(torch.ones(5,5))
tensor

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [26]:
torch.tril(torch.tensor([[1,2,3],[4,5,6]]), diagonal=1)

tensor([[1, 2, 0],
        [4, 5, 6]])

In [27]:
torch.triu(torch.tensor([[1,6],[7,8],[9,5],[4,7]]), diagonal=0)

tensor([[1, 6],
        [0, 8],
        [0, 0],
        [0, 0]])

In [28]:
input_tensor = torch.tensor([[1,6],[7,8]])
masked_tensor = torch.tensor([[True, False], [True, True]])

torch.masked_fill(input_tensor, masked_tensor, value=1)

tensor([[1, 6],
        [1, 1]])

In [29]:
input = torch.zeros(2,3,4)
output = input.transpose(0, 2)
output.shape

torch.Size([4, 3, 2])

In [30]:
input

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [31]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,6,8])
tensor_3 = torch.tensor([9,3,5])

stacked_tensor = torch.stack([tensor_1, tensor_2, tensor_3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 6, 8],
        [9, 3, 5]])

In [32]:
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))

tensor([-7.2092, -6.4121, -8.4083], grad_fn=<SqueezeBackward4>)


In [33]:
tensor1 = torch.tensor([1., 2., 3.])
softmax_output = F.softmax(tensor1, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [ ]:

# Define vocabulary size and embedding dimension
vocab_size = 10000
embedding_dim = 100

# Create an embedding layer
embedding = nn.Embedding(vocab_size, embedding_dim)

# Example input sequence
input_sequence = torch.LongTensor([1, 5, 7, 3, 2])

# Pass input through the embedding layer
embedded_sequence = embedding(input_sequence)

print(embedded_sequence.shape)
print(embedded_sequence)



In [37]:
# Matrix multiplication
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [39]:
int_64 = torch.randint(5, (3,2)).float()
float_32 = torch.rand(2,3)
print(torch.matmul(int_64, float_32))

tensor([[3.5606, 4.1922, 5.5632],
        [2.5742, 2.2175, 3.6299],
        [2.1733, 3.3721, 3.7876]])
